version: '3.3'

services:
    cosmetic-eureka-service:
        build:
            context: ./cosmetic-eureka-service/
            dockerfile: Dockerfile
        container_name: eureka-service
        ports:
            - "8761:8761"
        restart: always
        
    cosmetic-common:
        build:
            context: ./cosmetic-common/
            dockerfile: Dockerfile
        container_name: common
    cosmetic-setup-service:
        build:
            context: ./cosmetic-setup-service/
            dockerfile: Dockerfile
        depends_on: 
            - cosmetic-common
        container_name: setup-service
        ports:
            - "8080:8080"
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: cosmetic
            MYSQL_USER: root
            MYSQL_PASSWORD: root
            MYSQL_HOST: localhost
            MYSQL_PORT: 3306
        network_mode: host
        volumes:
            - cosmetic-db:/var/lib/mysql
    
volumes:
    cosmetic-db: