spring:
  application:
    name: cosmetic-setup-service
  cache:
     type: redis
  redis:
     host: localhost
     port: 6379
  datasource:
      url: jdbc:mysql://localhost:3306/cosmetic
      driverClassName: com.mysql.cj.jdbc.Driver
      username: root
      password: root
  jpa:
      properties:
         hibernate:
            dialect: org.hibernate.dialect.MySQL55Dialect
      hibernate:
         ddl-auto: update  
  servlet:
      multipart:
         enabled: true
         max-file-size: 10MB        

server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
    
image:
   filePath: /home/cosmetic_images/   

logging:
   level:
      org.hibernate.SQL: DEBUG
      org.hibernate.type.descriptor.sql.BasicBinder: TRACE   
    